### ISSUE TITLE
track collision tool

### ISSUE THREAD

**Issue by selo920** [mrwonko/fo2re#1]
have you maybe had the privilege to download this tool when it was concieved first here? 

http://community.bugbeargames.com/threads/track-collision-modding-tool.9782/

the link is dead. the owner of the mod is inactive to high hell. only repository shared of his(just a few posts below in the thread) is not the same tool. you seem to have some repositories in your hand and im curious to know if you have any information regarding to this one, too.

We have a very small active community over on discord trying to keep flatout joint going but there arent much we can do other than cars and textures. if you would like to take a peek, here is the link. https://discord.gg/pWJb7xt9p7

**Comment by mrwonko** [comment]
The tool has since been unearthed and is available on the linked Discord, which I have now joined.
